//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Id { get; set; }
        public string Detail { get; set; }
        public string FilePath { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> MissingId { get; set; }
        public byte[] Photo1 { get; set; }
        public Nullable<bool> IsPhoto { get; set; }
    }
}
